### ISSUE TITLE
Can't install repo-master.zip

### ISSUE THREAD

**Issue by philled** [xbmc-catchuptv-au/repo#10]
I'm trying to install the file repo-master.zip into Kodi 14.2 using "Install from zip file". When I select the file to install it I get an error saying "Add-on does not have the correct structure".

I has assumed that this file would install the repository for all of the xbmc-catchuptv-au add-ons to make it easier to install them all. 

If I unzip -l the file I can see all the contents so I don't think it's got corrupted in downloading. Have I misunderstood what this file is for, or is there a problem with it? Perhaps it's not compatible with version 14.2 of Kodi?

**Comment by andybotting** [comment]
Don't install the repo master zip file - Kodi is correct, it isn't the
right structure.

Grab the one listed in the github repo project.

Cheers

**Comment by philled** [comment]
Sorry, but I don't think I understand what you're saying "Grab the one listed in the github repo project". I then downloaded repository.googlecode.xbmc-catchuptv-au-1.3.zip from https://github.com/xbmc-catchuptv-au/repo/tree/master/repository.googlecode.xbmc-catchuptv-au but when I tried installing this I got the same error. 

Could you please point me to where you mean by "the one listed in the github repo project".

**Comment by andybotting** [comment]
Hi @philled,

Sorry, I bashed out the last message rather quickly on my phone.

The ZIP file you want is:
https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/repository.googlecode.xbmc-catchuptv-au-1.3.zip

Using this one, paired with the instructions at:
https://github.com/xbmc-catchuptv-au/repo/blob/master/README.md

should get you over the line.
