### ISSUE TITLE
HD/SD?

### ISSUE THREAD

**Issue by davebelling** [xbmc-catchuptv-au/repo#15]
Hi. Love your work. Just a comment about the resolution of the video streams. It shows up as SD when viewing the program list on our OpenElec install but the quality is pretty bad. I've seen pretty high definition catchup on display televisions in stores, is there a limitation to what the available streams can do? Thanks.

**Comment by andybotting** [comment]
It's all about knowing how to access the stream. If you can give a specific example, I can take a look, but it's often a lot of work to try and reverse-engineer how a particular streaming service works.

**Comment by davebelling** [comment]
Thanks for the reply.

Myself and a few guys at work attempted to get the streams using wireshark but it was very tricky. It seems to come in bits. He has the latest LG TV with Freeview Plus so I might get him to try there. If I find anything I'l let you know.

**Comment by andybotting** [comment]
Yeah, it's super tricky. Makes it even harder now that they generally use HTTPS, so you can't see the payload between a new smart TV and the streaming service without some really clever stuff.

You should have seen what I had to do to get Plus7 to work... ouch

**Comment by davebelling** [comment]
It's like they don't want us to win. I have some cluey guys around, we'll keep cracking on with it.
