### ISSUE TITLE
Latest version show incompatible

### ISSUE THREAD

**Issue by brettalcorn** [xbmc-catchuptv-au/repo#16]
Hi Andy,

The latest update via addon.xml comes up as "Incompatible" for 4 addons: ABC iView, Ninemsn Jump-In, NRL Video and TENplay. Kodi reports "Add-on is incompatible or has been marked broken in repository"

Anyway I was able to install the ABC iView plugin directly using plugin.video.abc_iview-1.6.8.zip and verified that it works. Probably the others do too, although I haven't checked.

OpenELEC 5.0.8 (Kodi 14.2)

- Brett

**Comment by andybotting** [comment]
Hi Brett,

I'll have a look and get back to you.

cheers

**Comment by andybotting** [comment]
Just tested this on my RPi2 with OpenELEC 5.0.8, and it worked perfectly. Can you confirm it's still not working?

**Comment by brettalcorn** [comment]
Sorry for the very long delay in responding. I just rebuilt an older HTPC (Asus Revo) with OpenELEC 5.0.8 and it worked fine. Not sure what was wrong earlier! Thanks for checking anyway.

**Comment by andybotting** [comment]
OK great. Thanks for letting me know
