### ISSUE TITLE
No add-ons visible

### ISSUE THREAD

**Issue by kentcb** [xbmc-catchuptv-au/repo#18]
I must be doing something silly...

I'm using latest OpenELEC (5.0.8) on Cubox-i.

I've successfully installed the repo and can see it under System/Settings/Add-ons/Enabled Add-ons/Add-on repository. However, I don't see "Catch-Up TV AU" under System/Settings/Add-ons, which is what the readme specifies. In fact, I can't see it anywhere.

Can you please tell me what I'm doing wrong?

**Comment by andybotting** [comment]
Good question. That should be enough.

This is a good guide, if you want to double check your steps:
http://www.openmediacentre.com.au/tutorials/xbmckodi/installing-catchup-tv-au-repo-and-add-ons/

Tried all the usual things, like removing the repo and installing again, rebooting, etc?

**Comment by kentcb** [comment]
Ah, I was right about doing something silly, but the readme is misleading. One must go to *Get Add-ons*, but the readme does not mention that. Also, the Kodi add-on UI confuses the hell out of me every time I use it. I don't understand why it's not just a filterable list, but maybe it's just me.

Alas, my main desire was for SBS catchup, but they're borked that.

Thanks for the help.
