### ISSUE TITLE
Bufffering

### ISSUE THREAD

**Issue by meteordust** [xbmc-catchuptv-au/repo#23]
Hi,

With my Kodi 15.2 on a RPI2 have too much buffering (every 20 seconds). When I pause the stream like Plus7 I also don't see that Openelec/Kodi buffering any content like it does with all other Genesis, movies from NAS etc. Have buffer method in advancedsettings on 1, so it should buffer everything.
Is this a problem on my side or does Catch Up not using the buffer and working like a live (direct) stream.
When I watch with my computer from the yahoo plus 7 catchup website I dont have any problem at all. BTW using a VPN connection but using the same one on my computer.

With regards,

Sander

**Comment by andybotting** [comment]
We don't control the buffering in the add-on, so it must be done some other
way.

Are you using the same setup (e.g. Kodi w/Plus 7 and VPN) on your desktop
too?

**Comment by meteordust** [comment]
Hi Andy,

Thanks for your reply, the difference in setup is that the windows 10 computer is using the PIA manager, so in that case Kodi is not using the unofficial OpenVPN like on my RPI2. the windows PIA manager also using OpenVPN in their software btw..

With my RPI2/ OpenVPN I don't have any issue with streaming with other Add-on, only Catchup causing buffering every 10-20 seconds, that is on Openelec 5.0.8 and the latest 6.0.0

Have also an advancedsettings.xml to buffer all possible files and buffer enough to play without problems.

My thought is now that probably the combination with RPI2, VPN, Catchup and my location in the Netherlands is maybe too much to ask, but a speedtest over the Sydney VPN to the Netherlands gives me more then enough juice to play any stream like it does on my windows 10 system, and think that more not AU located people streaming with Kodi using Catchup and hoped others had a problem like this and maybe a solution.

Hope you can show me the right direction.

Regards,

Sander

**Comment by andybotting** [comment]
I had the same sort of issues when watching iView when I lived in the UK.
It's not about bandwidth for streaming video - it's more about latency.

I think from memory, Plus7 uses adaptive streaming, so you're only going to
be able to buffer whatever the server gives you. My understanding is that
the server only gives you a bit at a time so it can adjust the quality as
you go.

If you go into the addon settings, you can change the streaming method.
Have you tried the 'native' method?

**Comment by meteordust** [comment]
Yes it is on the native method, Kodi 14+.

**Comment by meteordust** [comment]
So could it be possible that the build in OpenVPN in Kodi on a RPI2 can cause this latency and on my windows Kodi not cause of the VPN connection outside Kodi?

**Comment by meteordust** [comment]
The best way to describe this is that after buffering to 100% it starts playing, losing the connection and start buffering again to 100% and starts playing again.

**Comment by meteordust** [comment]
Hi Andy,

Just wanted to let you know that you right about the latencies and bandwidth, found out that buffering stops when I reduce the internet access speed in Kodi/system settings to 512 kbps, had some reading on the Plus7 site and they mention that the quality depends on your bandwidth, minimum 300 kbps and 1500 kbps recommended like you said.

About the latencies, in my PIA manager on my windows computer I have a latencies file that I don't have on my RPI2, I assume that this is the delay time between two connections..
Ping to Melbourne/Sydney is about 450 ms, checked it with speedtest.net. Download speed is about 15Mbps from Melbourne to the Netherlands, Mine ISP speed is 120Mbps.

Still wondering around why I don't have the buffer problem on my windows computer with of course OpenVPN not running within Kodi itself and why I get buffering problems with higher bandwidth on the RPI2.

With ABC Iview don't have the buffer problem but the quality looks lower then I have now with Plus7 on 512 kbps.

Hope I don't bother you too much with his.....

Regards, Sander

**Comment by Dcellwood** [comment]
Hi running Kodi 15.2 on Fire TV Stick in the UK. I have installed the AU Catch-up TV repository for the NRL add on. Have the add on installed and the content immediately streams. Within seconds I get the following error:

Cache filled before reaching required amount. 

The stream then staggers, audio disappears and becomes unwatchable. This is the only add on that does this? I have tried setting the device to zero cache and also reducing the quality setting within the app to its lowest but the problem remains. 

Can you help as the content is excellent and it's a real shame. 

Thanks 

Dave

**Comment by andybotting** [comment]
Hi Dave,

Unfortunately we can only get a really high resolution feed from NRL, which
will totally choke with the latency of UK to AU.

I did have a look recently to see if there was anything I could do, but I
couldn't discover any way to obtain a lower res stream. I even have trouble
on a good ADSL connection here in Aus.

Cheers,
Andy

**Comment by Dcellwood** [comment]
Thanks for the reply Andy. It's a real shame as the content is quality. Are you aware of any alternative addons with NRL content?
