### ISSUE TITLE
Add footy shows to the AFL video addon?

### ISSUE THREAD

**Issue by demidog** [xbmc-catchuptv-au/repo#36]
Hi Andy,

Would it be worth adding footy shows from different channels to the AFL video addon?
for example Talking footy, Friday front bar and Game Day from Plus7 and Marngrook footy show from SBS.

**Comment by andybotting** [comment]
Nice idea, but too much work at this stage. TBH, I'd love to be able to combine all the streaming services into one and have one massive list of shows to pick from, but not really feasible.
