### ISSUE TITLE
Unable to Install Australia Catch Up TV

### ISSUE THREAD

**Issue by StickyW99** [xbmc-catchuptv-au/repo#43]
I have downloaded the Zip file and put in a Folder named Kodi on my Desktop.

Try to install from zip file using System-Settings-Addons-Install from Zip File

Get an error message -- Unable to install from Zip file

All and any advice appreciated.

PS>  I am using a Macbook Pro

**Comment by andybotting** [comment]
Does Mac OS X extract the zip file automatically when you download it? I've had trouble with that before.
