### ISSUE TITLE
Problem Installing CatchupTV Repository

### ISSUE THREAD

**Issue by pollardd** [xbmc-catchuptv-au/repo#46]
Hi There,
I'm trying to install catchup TV on Kodi/Xbmc running on my Raspberry Pi With OpenElec,
I have installed other repositories no problem.
Rather than download the file and copy it to the system which isn't that easy the recommended procedure seems to be to add the full https:// reference to the zip file using System -> FileManager then install from zip using System -> Settings -> Add Ons -> Install From Zip File.

I can see the zip file listed with the name I gave it along with other things already installed.
When I select it I see the sub folder within the zip named "repository.googlecode.xbmc-catchuptv-au"
Cancel is the only button enabled.
If I open that folder All I see is the .. parent folder item with Cancel being the only button enabled.

I downloaded the same zip file to my windows pc when I opened it I could see an XML file and an icon file.  I assume that is all that should be in there.
Any ideas why I can't install from the zip file?

Thanks 
David

**Comment by pollardd** [comment]
I think I figured it out.  I needed to put the folder path to the zip and not the zip itself.
Once I did that the zip was able to be selected and installed.  So all good now.

**Comment by andybotting** [comment]
Ok, glad you got it sorted out. I wish there was an easier process for this.
