### ISSUE TITLE
Can't get to the catchuptv au repository

### ISSUE THREAD

**Issue by tigsboy** [xbmc-catchuptv-au/repo#49]
Hi.
Trying to install the catchuptv-au addon for Kodi, via an amazon firestick plugged into the back of the TV. I've had no problem installing other addons, internet connection is ok.

I've tried various versions from "file manager >> add source" but all have not worked. It will let me create the source, but there are no sub directories and no zip to find. I can find the source when I try to "install from zip file" but it is blank. I've tried the following combinations in the "add source" area to try and navigate to the zip. Is there something I'm doing wrong. I've followed the tutorials and as I said, I've installed lots of other addons.

https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/repository.googlecode.xbmc-catchuptv-au-1.3.zip

https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/

https://github.com/xbmc-catchuptv-au/repo/raw/master/

https://github.com/xbmc-catchuptv-au/repo/raw/

https://github.com/xbmc-catchuptv-au/repo/

https://github.com/xbmc-catchuptv-au/

https://github.com/

**Comment by andybotting** [comment]
Would be interesting to see your log file, as it might shed some light on why Kodi doesn't like it.

If you could follow the log upload guide here: http://kodi.wiki/view/Log_file/Easy and let me know the URL it uploads it to, I'll take a look.

**Comment by tigsboy** [comment]
Thanks Andy.

Https://paste.ubuntu.com/23940633/.

I only did the following url's. amended them in the add source area. And tried to "install from zip file"

https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/repository.googlecode.xbmc-catchuptv-au-1.3.zip

https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/

**Comment by tigsboy** [comment]
correction:

Should be 👍 
Thanks Andy.

Https://paste.ubuntu.com/23940622/.

**Comment by andybotting** [comment]
Did you try downloading the zip file to the device, then using 'Install from Zip file' and choosing the zip file from the file manager?

**Comment by tigsboy** [comment]
Andy.
Sorry its a firestick and i don't know how to download directly to it.
Any suggestions.

Sent from Yahoo7 Mail on Android 
 
  On Mon, 6 Feb, 2017 at 19:15, Andy Botting<notifications@github.com> wrote:   
Did you try downloading the zip file to the device, then using 'Install from Zip file' and choosing the zip file from the file manager?

**Comment by andybotting** [comment]
OK, I have a solution for you.

Follow the instructions here: https://github.com/MediaBrowser/plugin.video.emby/wiki/Emby-Repository but use the following URL instead:
http://www.andybotting.com/~andy/kodi

You should be able to find the repo zip file repository.googlecode.xbmc-catchuptv-au-1.3.zip

Good luck
