### ISSUE TITLE
SBS script error on OpenElec 4.0.3 / XBMC 13.1 / RPi

### ISSUE THREAD

**Issue by wyrdR** [xbmc-catchuptv-au/repo#5]
Just wondering how I can contribute to getting this one working again.
Not sure if this is OpenElec / Raspberry Pi specific. 

Was not working in XBMC 12.1 either.

Please advise how I can provide more useful information.

TA
~ wyrdR

**Comment by andybotting** [comment]
We now have a new SBS OnDemand addon, I'll close this ticket.
