### ISSUE TITLE
ABC news 24 addon isn't compatible with Krypton

### ISSUE THREAD

**Issue by alexmustafa** [xbmc-catchuptv-au/repo#50]

**Comment by andybotting** [comment]
We're not maintaining that addon any more. 

We will soon be publishing an update the to the main iView addon, which will include support for the live streams. You can pull a development version from here if you would like to test it:
https://github.com/andybotting/xbmc-addon-abc-iview/archive/mobile-api.zip

cheers

**Comment by unlocKing** [comment]
I can't see the live section in this - is it in this release?

**Comment by andybotting** [comment]
:1st_place_medal:

**Comment by alexmustafa** [comment]
Thanks Andy, will try it out.
