### ISSUE TITLE
AFL VIDEO WONT STREAM LIVE ERROR 400

### ISSUE THREAD

**Issue by marcopolosas** [xbmc-catchuptv-au/repo#53]
hi i am having trouble live streaming afl. all my account details are correct but i keep getting ERROR400?

can anyone help?

Thanks

**Comment by ihp62** [comment]
AFL TV not streaming on version 1.72 under Krypton. Error message is 'streams'

**Comment by andybotting** [comment]
@marcopolosas Please try the latest version, v1.7.3. It supports BOTH Telstra customer free subscription AND a paid subscription through the AFL. The older version only supported the Telstra subscription.

If you have a Telstra subscription and it's not working, please check to make sure your account is working by logging in to this URL:
https://hub.telstra.com.au/sp2017-afl-app.html?device=desktop
You need to make sure your mobile number is listed next to 'Current service: ' and these settings are all correct in the add-on settings.

**Comment by sdt** [comment]
:million-thumbs-up:

Works perfectly for me. 50Hz and all. Excellent work sir! Thank you so much.
