### ISSUE TITLE
abc_iview 1.8.0 crashes on start under LibreElec 8.0.2 / Kodi 17.3

### ISSUE THREAD

**Issue by LibreGoose** [xbmc-catchuptv-au/repo#60]
I have plugins set to autoupdate.  The ABC iView plugin stopped working when it autoupdated to 1.8.0.

I haven't investigate much yet, but thought that I'd post the log here as a starting point.

   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                      
                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                
                   Error Type: <type 'exceptions.ImportError'>                                                                     
                   Error Contents: No module named requests                                                                        
                   Traceback (most recent call last):                                                                              
                     File "/storage/.kodi/addons/plugin.video.abc_iview/default.py", line 31, in <module>                          
                       import utils, categories, series, programs, play                                                            
                     File "/storage/.kodi/addons/plugin.video.abc_iview/resources/lib/categories.py", line 24, in <module>         
                       import comm                                                                                                 
                     File "/storage/.kodi/addons/plugin.video.abc_iview/resources/lib/comm.py", line 20, in <module>               
                       import requests                                                                                             
                   ImportError: No module named requests                                                                           
                   -->End of Python script error report<--                                                                         
   ERROR: GetDirectory - Error getting plugin://plugin.video.abc_iview/                                                            
   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.abc_iview/) failed

**Comment by andybotting** [comment]
OK, so looks like it can't find the requests library, which is required. Most of our add-ons use the requests library - do you have any of them installed, like AFL Video for example?

**Comment by LibreGoose** [comment]
The only other plugin that I had installed was the SBS catchup.  It fails with the same problem.

I'm just in the middle of uninstalling the catchup plugins and re-installing them.

**Comment by LibreGoose** [comment]
This isn't a bug in the catchupvt-au plugin

The requests module is somehow missing from python in the Kodi 17.3 / LibreElect build for the raspberry pi.

To fix the problem I went to http://mirrors.kodi.tv/addons/krypton/script.module.requests/
and downloaded:  script.module.requests-2.12.4.zip

The I installed the same way that the catchuptv repository is installed.

Addins -> choose the little box icon at the top of the 17.3 menu -> Install from Zip -> "my usb stick" -> script.module.requests-2.12.4.zip

Suddenly cathuptv-au works again.

Thanks Andy for responding - this isn't a bug in your awesome add-on. 

My 4 YO sends you his love.  ABC4Kids is back :)

**Comment by andybotting** [comment]
That's great. We actually include requests in our repo here: https://github.com/xbmc-catchuptv-au/repo/tree/master/script.module.requests

Why you couldn't pull that in via the repository is the interesting thing,

**Comment by LibreGoose** [comment]
I think it is some sort of general Kodi - python error.  I googled the "ImportError: No module named requests" problem and got heaps of hits for all different versions of Kodi/XBMC since 2012 with all sorts of different plugins.

Given the wide usage of "requests" in python scripts, I don't understand why it is even a separate installable thing.  It is so widely used it should just be one of the python pre-reqs for kodi itself.  Or better still: just something built into the base install of python.

**Comment by glennguy** [comment]
@andybotting I know why this has happened, it happened to me when updating NRL - even though we have the import requirements listed in the iview addon.xml, it needs to be added to addons.xml in the repo. I'm about to make a PR for my changes to iview so if your happy with your review we could make a release and fix this at the same time.
