### ISSUE TITLE
plus7 Android error. wont open

### ISSUE THREAD

**Issue by nazofm** [xbmc-catchuptv-au/repo#62]
17:21:11.976 T:18446744071930419504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'Android'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plus7/default.py", line 27, in <module>
                                                import drmhelper
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.drmhelper/lib/drmhelper.py", line 51, in <module>
                                                ssd_filename = drmconfig.SSD_WV_DICT[system_]
                                            KeyError: 'Android'
                                            -->End of Python script error report<--
17:21:12.435 T:18446744072427510064   ERROR: GetDirectory - Error getting plugin://plugin.video.plus7/
17:21:12.443 T:18446744072427510064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plus7/) failed
17:22:17.648 T:18446744072427510064  NOTICE: Samba is idle. Closing the remaining connections

**Comment by glennguy** [comment]
Hey @nazofm 
I should have a fix pushed up shortly.

**Comment by glennguy** [comment]
@nazofm Just pushed updated drmhelper to the repo. It will take around 5 minutes for the changes to make its way through all of github. So after then go to addons > my addons > add-on repository and bring up the context menu/long press on XBMC CatchupTV AU and select check for updates. Should be good to go then! 😄

**Comment by nazofm** [comment]
legend thanks @glennguy i will let you know how I go

**Comment by nazofm** [comment]
all good now :)

**Comment by glennguy** [comment]
Awesome, will close the issue
