### ISSUE TITLE
Cannot install iview - failed to install dependencies - fresh Kodi install

### ISSUE THREAD

**Issue by stuger** [xbmc-catchuptv-au/repo#66]
Hi

I have installed the repo (using repo.zip).  When I try to install the iview plugin through the repository I receive an error that plugin.video.abc_iview-1.8.4.zip cannot be downloaded and that dependency script.module.aussieaddonscommon-1.1.1.zip failed to download.

Here is the relevant part of the log:

ERROR: CCurlFile::Open failed with code 404 for https://github.com/xbmc-catchuptv-au/repo/script.module.aussieaddonscommon/script.module.aussieaddonscommon-1.1.1.zip
08:35:24.260 T:1628   ERROR: CAddonInstallJob[script.module.aussieaddonscommon]: failed to download special://home/addons/packages/script.module.aussieaddonscommon-1.1.1.zip
08:35:24.263 T:1628   ERROR: CAddonInstallJob[plugin.video.abc_iview]: failed to install dependency script.module.aussieaddonscommon

It looks like the install is not pointing to the correct GitHub address.  That is, plugin.video.abc_iview-1.8.4.zip is accessible (via web browser) from "... repo/blob/master/" but the download pathway when installing is directed only to /repo/ ... and not /repo/blob/master.  

If you try to access the path set by the installer (shown in the logs) ( https://github.com/xbmc-catchuptv-au/repo/script.module.aussieaddonscommon/script.module.aussieaddonscommon-1.1.1.zip) in a web browser you get a 404 error.

**Comment by andybotting** [comment]
Sounds very strange, and I'm not sure why you're not seeing the correct URL. I'll test this out as soon as I can and get back to you.

**Comment by glennguy** [comment]
@stuger are you still having this issue? If so could we get a full debug log to have a look at?

**Comment by supabro** [comment]
I get the same issue with 9now, ABC iView, 7Plus.


Clicking on the lin in the original post comes back with File Not Found.  (Go one, you know you want to click it). 

So the script points to
https://github.com/xbmc-catchuptv-au/repo/script.module.aussieaddonscommon/script.module.aussieaddonscommon-1.1.1.zip

When it should be pointing to
https://github.com/xbmc-catchuptv-au/repo/blob/master/script.module.aussieaddonscommon/script.module.aussieaddonscommon-1.1.1.zip

**Comment by andybotting** [comment]
Sup bro. Can you tell me what platform you're using?

**Comment by supabro** [comment]
Hiya Andy, Android TV (Sony). 

Firstly thanks for everything. Note Ch10 , SBS, Netball TV all worked.

Sorry new to GitHub. I can grab logs from kodi, but where do I upload?

**Comment by andybotting** [comment]
The guide is here. Super easy with the Log Uploader add-on:
http://kodi.wiki/view/Log_file/Easy

I've just done a test here on Linux and it worked OK. I'll try on Android TV also then.

We might be using URLs a little inconsistently, so I'm going to go through them and try and standardise a bit.

If you're interested, I'd recommend trying out our development repository. The details for it are here: http://aussieaddons.com/development/

This uses a newer, better style of URLs, so it may work better for you. I'd be interested to see if it makes a difference in your situation.

**Comment by supabro** [comment]
Hi Andy,  Thanks for the help,

Here's the log dump  I tried Nine, ABC, Seven  starts line 1335.  
https://paste.ubuntu.com/26136958/

from 1342-47
13:51:50.165 T:18446744071970990384 DEBUG: CCurlFile::Open - effective URL: <https://raw.githubusercontent.com/xbmc-catchuptv-au/repo/master/script.module.drmhelper/script.module.drmhelper-1.0.9.zip.md5> 13:51:50.166 T:18446744071954827568 DEBUG: Thread FileCache start, auto delete: false 13:51:50.166 T:18446744071954827568 INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?) 13:51:50.216 T:18446744071954827568 DEBUG: Thread FileCache 18446744071954827568 terminating 13:51:50.217 T:18446744071970990384 ERROR: CAddonInstallJob[plugin.video.catchuptv.au.nine]: failed to install dependency script.module.drmhelper 13:51:50.227 T:18446744072427956528 DEBUG: ------ Window Init (DialogNotification.xml) ------


i'll try the devRepo in a bit & let you know.

**Comment by glennguy** [comment]
Hey @supabro 
I think I can see the problem here just a few lines before your paste:
```
13:51:48.469 T:18446744072427956528   DEBUG: CAddonInstaller: installing 'plugin.video.catchuptv.au.nine' version '1.0.0' from repository 'repository.googlecode.xbmc-catchuptv-au'
13:51:48.482 T:18446744072427956528   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
13:51:48.538 T:18446744071970990384   DEBUG: CFileCache::Open - opening <v7/addons/script.module.drmhelper/script.module.drmhelper-1.0.9.zip.md5> using cache
13:51:48.538 T:18446744071970990384   DEBUG: CurlFile::Open(0xb91065f0) http://redirect.superrepo.org/v7/addons/script.module.drmhelper/script.module.drmhelper-1.0.9.zip.md5
13:51:48.539 T:18446744071970990384    INFO: easy_aquire - Created session to http://redirect.superrepo.org
13:51:48.790 T:18446744072427956528   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
13:51:48.792 T:18446744072427956528   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
13:51:50.165 T:18446744071970990384   DEBUG: CCurlFile::Open - effective URL: <https://raw.githubusercontent.com/xbmc-catchuptv-au/repo/master/script.module.drmhelper/script.module.drmhelper-1.0.9.zip.md5>
13:51:50.166 T:18446744071954827568   DEBUG: Thread FileCache start, auto delete: false
13:51:50.166 T:18446744071954827568    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
13:51:50.216 T:18446744071954827568   DEBUG: Thread FileCache 18446744071954827568 terminating
13:51:50.217 T:18446744071970990384   ERROR: CAddonInstallJob[plugin.video.catchuptv.au.nine]: failed to install dependency script.module.drmhelper
```

It looks like Kodi is finding the drmhelper addon dependency available from your superrepo repository which is incorrectly redirecting and giving us the 404. Try disabling/uninstalling superrepo and trying to install again and let us know how you go.

**Comment by supabro** [comment]
hiya Glenn!

Thanks for the quick reply!  You;re right on the money. I disable the 3 SuperRepo repo's, uninstalled & re-installed 9Now from the normal Catchu TV AU repo (not the dev) and it worked (and found some content which wasn't DRM'd & would play).

Thanks again Andy & Glenn for your quick response & help, much appreciated.

**Comment by andybotting** [comment]
Great news. I'll add this to our FAQ I think.

So we've been picked up by SuperRepo and TV Addons - and conflict with Ares. Ugh
