### ISSUE TITLE
Can't load repo in Helix (14.2)

### ISSUE THREAD

**Issue by supernano** [xbmc-catchuptv-au/repo#7]
Just installed the latest XBian on my Pi with Kodi 14.2. When I try to load the repo-master file I get "addon does not have the correct structure"

**Comment by andybotting** [comment]
Use this one, not master:

https://github.com/xbmc-catchuptv-au/repo/raw/master/repository.googlecode.xbmc-catchuptv-au/repository.googlecode.xbmc-catchuptv-au-1.3.zip

Let me know how that goes

**Comment by AndrewG-W** [comment]
I can't seem to get the addon to install on Kodi 14.2 either. I've also tried the zip you linked to above.

**Comment by shauntrigger** [comment]
Hi Andy Just like to say amongst all the emails you get for the repo not working you don't get to here from the people that it is working, so just letting u know mine is working great and has never been better in 14.2, so thank you for your hard work and keep it up Andy

**Comment by andybotting** [comment]
Cheers @shauntrigger 

@AndrewG-W I can't see any issues here. Just tried it myself again and no issues. Can you just check that when you open up that ZIP file, you see 'repository.googlecode.xbmc-catchuptv-au' in the root?

Do you see the "addon does not have the correct structure" message?

**Comment by AndrewG-W** [comment]
Hi All, sorry, rebooted the pi and everything worked perfectly.. sorry for false alarm.

**Comment by andybotting** [comment]
Glad it's sorted for you @AndrewG-W  :)

**Comment by supernano** [comment]
Sorry for the late reply, I was away last week. The zip in the link worked fine. Thanks a lot!
