### ISSUE TITLE
Kodi web site refers to googlecode for repo

### ISSUE THREAD

**Issue by philled** [xbmc-catchuptv-au/repo#9]
I've been using your excellent CatchUP TV add-ons for a while. I've noticed that the Kodi web page for Unofficial add-on repositories lists the CatchUP TV repo as being at https://code.google.com/p/xbmc-catchuptv-au/downloads/list?q=label:repo-installer. Presumably that is out of date as the code now lives on GitHub. This is a little bit confusing for some as it's not very clear whether the home for this project is GoogleCode or GitHub. Shall I update the link on that wiki page to point to https://github.com/xbmc-catchuptv-au/repo/archive/master.zip ?

**Comment by andybotting** [comment]
I meant to do it some time ago, but the wiki requires authorisation by a real person, so it took some time and I forgot about it. 

I also wanted to modify the entry a little too, so I've just done it now. Thanks for the reminder!
